// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bcbm.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息枚举
type MessageID int32

const (
	MessageID_MsgError        MessageID = 0
	MessageID_MsgPing         MessageID = 1
	MessageID_MsgPong         MessageID = 2
	MessageID_MsgLogin        MessageID = 3
	MessageID_MsgLoginR       MessageID = 4
	MessageID_MsgLogout       MessageID = 5
	MessageID_MsgLogoutR      MessageID = 6
	MessageID_MsgRoomChangeHB MessageID = 7
	MessageID_MsgJoinRoom     MessageID = 8
	MessageID_MsgJoinRoomR    MessageID = 9
	MessageID_MsgLeaveRoom    MessageID = 10
	MessageID_MsgLeaveRoomR   MessageID = 11
	MessageID_MsgGrabBanker   MessageID = 12
	MessageID_MsgAutoBet      MessageID = 13
	MessageID_MsgAutoBetR     MessageID = 14
	MessageID_MsgBet          MessageID = 15
	MessageID_MsgBetInfoB     MessageID = 16
	MessageID_MsgBankersB     MessageID = 17
	MessageID_MsgPlayers      MessageID = 18
	MessageID_MsgPlayersR     MessageID = 19
	MessageID_MsgRoomStatusB  MessageID = 20
)

var MessageID_name = map[int32]string{
	0:  "MsgError",
	1:  "MsgPing",
	2:  "MsgPong",
	3:  "MsgLogin",
	4:  "MsgLoginR",
	5:  "MsgLogout",
	6:  "MsgLogoutR",
	7:  "MsgRoomChangeHB",
	8:  "MsgJoinRoom",
	9:  "MsgJoinRoomR",
	10: "MsgLeaveRoom",
	11: "MsgLeaveRoomR",
	12: "MsgGrabBanker",
	13: "MsgAutoBet",
	14: "MsgAutoBetR",
	15: "MsgBet",
	16: "MsgBetInfoB",
	17: "MsgBankersB",
	18: "MsgPlayers",
	19: "MsgPlayersR",
	20: "MsgRoomStatusB",
}

var MessageID_value = map[string]int32{
	"MsgError":        0,
	"MsgPing":         1,
	"MsgPong":         2,
	"MsgLogin":        3,
	"MsgLoginR":       4,
	"MsgLogout":       5,
	"MsgLogoutR":      6,
	"MsgRoomChangeHB": 7,
	"MsgJoinRoom":     8,
	"MsgJoinRoomR":    9,
	"MsgLeaveRoom":    10,
	"MsgLeaveRoomR":   11,
	"MsgGrabBanker":   12,
	"MsgAutoBet":      13,
	"MsgAutoBetR":     14,
	"MsgBet":          15,
	"MsgBetInfoB":     16,
	"MsgBankersB":     17,
	"MsgPlayers":      18,
	"MsgPlayersR":     19,
	"MsgRoomStatusB":  20,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{0}
}

type AreaID int32

const (
	AreaID__AreaID   AreaID = 0
	AreaID_AreaID40x AreaID = 1
	AreaID_AreaID30x AreaID = 2
	AreaID_AreaID20x AreaID = 3
	AreaID_AreaID10x AreaID = 4
	AreaID_AreaID5x1 AreaID = 5
	AreaID_AreaID5x2 AreaID = 6
	AreaID_AreaID5x3 AreaID = 7
	AreaID_AreaID5x4 AreaID = 8
)

var AreaID_name = map[int32]string{
	0: "_AreaID",
	1: "AreaID40x",
	2: "AreaID30x",
	3: "AreaID20x",
	4: "AreaID10x",
	5: "AreaID5x1",
	6: "AreaID5x2",
	7: "AreaID5x3",
	8: "AreaID5x4",
}

var AreaID_value = map[string]int32{
	"_AreaID":   0,
	"AreaID40x": 1,
	"AreaID30x": 2,
	"AreaID20x": 3,
	"AreaID10x": 4,
	"AreaID5x1": 5,
	"AreaID5x2": 6,
	"AreaID5x3": 7,
	"AreaID5x4": 8,
}

func (x AreaID) String() string {
	return proto.EnumName(AreaID_name, int32(x))
}

func (AreaID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{1}
}

type ChipID int32

const (
	ChipID__ChipID    ChipID = 0
	ChipID_ChipID1x   ChipID = 1
	ChipID_ChipID10x  ChipID = 2
	ChipID_ChipID100x ChipID = 3
	ChipID_ChipID500x ChipID = 4
	ChipID_ChipID1kx  ChipID = 5
)

var ChipID_name = map[int32]string{
	0: "_ChipID",
	1: "ChipID1x",
	2: "ChipID10x",
	3: "ChipID100x",
	4: "ChipID500x",
	5: "ChipID1kx",
}

var ChipID_value = map[string]int32{
	"_ChipID":    0,
	"ChipID1x":   1,
	"ChipID10x":  2,
	"ChipID100x": 3,
	"ChipID500x": 4,
	"ChipID1kx":  5,
}

func (x ChipID) String() string {
	return proto.EnumName(ChipID_name, int32(x))
}

func (ChipID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{2}
}

type RoomStatus int32

const (
	RoomStatus__RoomStatus RoomStatus = 0
	RoomStatus_RSBetting   RoomStatus = 1
	RoomStatus_RSLottery   RoomStatus = 2
	RoomStatus_RSClear     RoomStatus = 3
)

var RoomStatus_name = map[int32]string{
	0: "_RoomStatus",
	1: "RSBetting",
	2: "RSLottery",
	3: "RSClear",
}

var RoomStatus_value = map[string]int32{
	"_RoomStatus": 0,
	"RSBetting":   1,
	"RSLottery":   2,
	"RSClear":     3,
}

func (x RoomStatus) String() string {
	return proto.EnumName(RoomStatus_name, int32(x))
}

func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{3}
}

// 错误码
type ErrorCode int32

const (
	ErrorCode_Success                       ErrorCode = 0
	ErrorCode_InsufficientBalanceGrabBanker ErrorCode = 101
	ErrorCode_InsufficientBalanceBet        ErrorCode = 102
	ErrorCode_ServerClosed                  ErrorCode = 201
	ErrorCode_UserRepeatLogin               ErrorCode = 202
	ErrorCode_UserRemoteLogin               ErrorCode = 203
	ErrorCode_UserNotInRoom                 ErrorCode = 301
	ErrorCode_UserAlreadyInRoom             ErrorCode = 302
	ErrorCode_RoomNotExist                  ErrorCode = 303
	ErrorCode_RoomFull                      ErrorCode = 304
	ErrorCode_NotInBetting                  ErrorCode = 401
)

var ErrorCode_name = map[int32]string{
	0:   "Success",
	101: "InsufficientBalanceGrabBanker",
	102: "InsufficientBalanceBet",
	201: "ServerClosed",
	202: "UserRepeatLogin",
	203: "UserRemoteLogin",
	301: "UserNotInRoom",
	302: "UserAlreadyInRoom",
	303: "RoomNotExist",
	304: "RoomFull",
	401: "NotInBetting",
}

var ErrorCode_value = map[string]int32{
	"Success":                       0,
	"InsufficientBalanceGrabBanker": 101,
	"InsufficientBalanceBet":        102,
	"ServerClosed":                  201,
	"UserRepeatLogin":               202,
	"UserRemoteLogin":               203,
	"UserNotInRoom":                 301,
	"UserAlreadyInRoom":             302,
	"RoomNotExist":                  303,
	"RoomFull":                      304,
	"NotInBetting":                  401,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{4}
}

// 心跳
type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

// 用户信息
type UserInfo struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Money                float64  `protobuf:"fixed64,2,opt,name=Money,proto3" json:"Money,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	WinCount             uint32   `protobuf:"varint,6,opt,name=WinCount,proto3" json:"WinCount,omitempty"`
	BetAmount            float64  `protobuf:"fixed64,5,opt,name=BetAmount,proto3" json:"BetAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserInfo) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfo) GetWinCount() uint32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

func (m *UserInfo) GetBetAmount() float64 {
	if m != nil {
		return m.BetAmount
	}
	return 0
}

// 房间信息
type RoomInfo struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	MinBet               float64  `protobuf:"fixed64,2,opt,name=MinBet,proto3" json:"MinBet,omitempty"`
	MaxBet               float64  `protobuf:"fixed64,3,opt,name=MaxBet,proto3" json:"MaxBet,omitempty"`
	MinLimit             float64  `protobuf:"fixed64,4,opt,name=MinLimit,proto3" json:"MinLimit,omitempty"`
	Status               uint32   `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Counter              uint32   `protobuf:"varint,6,opt,name=Counter,proto3" json:"Counter,omitempty"`
	EndTime              uint32   `protobuf:"varint,7,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	History              []uint32 `protobuf:"varint,8,rep,packed,name=History,proto3" json:"History,omitempty"`
	Statistics           []uint32 `protobuf:"varint,9,rep,packed,name=Statistics,proto3" json:"Statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{3}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomInfo) GetMinBet() float64 {
	if m != nil {
		return m.MinBet
	}
	return 0
}

func (m *RoomInfo) GetMaxBet() float64 {
	if m != nil {
		return m.MaxBet
	}
	return 0
}

func (m *RoomInfo) GetMinLimit() float64 {
	if m != nil {
		return m.MinLimit
	}
	return 0
}

func (m *RoomInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoomInfo) GetCounter() uint32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *RoomInfo) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoomInfo) GetHistory() []uint32 {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *RoomInfo) GetStatistics() []uint32 {
	if m != nil {
		return m.Statistics
	}
	return nil
}

// 登录游戏
type Login struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{4}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginR struct {
	User                 *UserInfo   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	RoomID               uint32      `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Rooms                []*RoomInfo `protobuf:"bytes,3,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
	ServerTime           uint32      `protobuf:"varint,4,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginR) Reset()         { *m = LoginR{} }
func (m *LoginR) String() string { return proto.CompactTextString(m) }
func (*LoginR) ProtoMessage()    {}
func (*LoginR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{5}
}

func (m *LoginR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginR.Unmarshal(m, b)
}
func (m *LoginR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginR.Marshal(b, m, deterministic)
}
func (m *LoginR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginR.Merge(m, src)
}
func (m *LoginR) XXX_Size() int {
	return xxx_messageInfo_LoginR.Size(m)
}
func (m *LoginR) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginR.DiscardUnknown(m)
}

var xxx_messageInfo_LoginR proto.InternalMessageInfo

func (m *LoginR) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginR) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *LoginR) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *LoginR) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 房间变化大厅广播
// Status = 2 表示 结算中 此状态时要显示 Result - 即最新的开奖结果
// Status = 1 表示 下注中 此状态时要显示进度条 - 用EndTime - ServerTime 可计算出进度条时长
type RoomChangeHB struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Counter              uint32   `protobuf:"varint,3,opt,name=Counter,proto3" json:"Counter,omitempty"`
	EndTime              uint32   `protobuf:"varint,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Result               uint32   `protobuf:"varint,5,opt,name=Result,proto3" json:"Result,omitempty"`
	Statistics           []uint32 `protobuf:"varint,6,rep,packed,name=Statistics,proto3" json:"Statistics,omitempty"`
	ServerTime           uint32   `protobuf:"varint,7,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomChangeHB) Reset()         { *m = RoomChangeHB{} }
func (m *RoomChangeHB) String() string { return proto.CompactTextString(m) }
func (*RoomChangeHB) ProtoMessage()    {}
func (*RoomChangeHB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{6}
}

func (m *RoomChangeHB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomChangeHB.Unmarshal(m, b)
}
func (m *RoomChangeHB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomChangeHB.Marshal(b, m, deterministic)
}
func (m *RoomChangeHB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomChangeHB.Merge(m, src)
}
func (m *RoomChangeHB) XXX_Size() int {
	return xxx_messageInfo_RoomChangeHB.Size(m)
}
func (m *RoomChangeHB) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomChangeHB.DiscardUnknown(m)
}

var xxx_messageInfo_RoomChangeHB proto.InternalMessageInfo

func (m *RoomChangeHB) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomChangeHB) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoomChangeHB) GetCounter() uint32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *RoomChangeHB) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoomChangeHB) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RoomChangeHB) GetStatistics() []uint32 {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func (m *RoomChangeHB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 登出游戏
type Logout struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout) Reset()         { *m = Logout{} }
func (m *Logout) String() string { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()    {}
func (*Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{7}
}

func (m *Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout.Unmarshal(m, b)
}
func (m *Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout.Marshal(b, m, deterministic)
}
func (m *Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout.Merge(m, src)
}
func (m *Logout) XXX_Size() int {
	return xxx_messageInfo_Logout.Size(m)
}
func (m *Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Logout proto.InternalMessageInfo

type LogoutR struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutR) Reset()         { *m = LogoutR{} }
func (m *LogoutR) String() string { return proto.CompactTextString(m) }
func (*LogoutR) ProtoMessage()    {}
func (*LogoutR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{8}
}

func (m *LogoutR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutR.Unmarshal(m, b)
}
func (m *LogoutR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutR.Marshal(b, m, deterministic)
}
func (m *LogoutR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutR.Merge(m, src)
}
func (m *LogoutR) XXX_Size() int {
	return xxx_messageInfo_LogoutR.Size(m)
}
func (m *LogoutR) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutR.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutR proto.InternalMessageInfo

// 加入房间
type JoinRoom struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom) Reset()         { *m = JoinRoom{} }
func (m *JoinRoom) String() string { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()    {}
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{9}
}

func (m *JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom.Unmarshal(m, b)
}
func (m *JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom.Marshal(b, m, deterministic)
}
func (m *JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom.Merge(m, src)
}
func (m *JoinRoom) XXX_Size() int {
	return xxx_messageInfo_JoinRoom.Size(m)
}
func (m *JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom proto.InternalMessageInfo

func (m *JoinRoom) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type JoinRoomR struct {
	CurBankers           []*UserInfo `protobuf:"bytes,1,rep,name=CurBankers,proto3" json:"CurBankers,omitempty"`
	Amount               []float64   `protobuf:"fixed64,2,rep,packed,name=Amount,proto3" json:"Amount,omitempty"`
	PAmount              []float64   `protobuf:"fixed64,3,rep,packed,name=PAmount,proto3" json:"PAmount,omitempty"`
	Room                 *RoomInfo   `protobuf:"bytes,4,opt,name=Room,proto3" json:"Room,omitempty"`
	History              []uint32    `protobuf:"varint,5,rep,packed,name=History,proto3" json:"History,omitempty"`
	ServerTime           uint32      `protobuf:"varint,6,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomR) Reset()         { *m = JoinRoomR{} }
func (m *JoinRoomR) String() string { return proto.CompactTextString(m) }
func (*JoinRoomR) ProtoMessage()    {}
func (*JoinRoomR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{10}
}

func (m *JoinRoomR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomR.Unmarshal(m, b)
}
func (m *JoinRoomR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomR.Marshal(b, m, deterministic)
}
func (m *JoinRoomR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomR.Merge(m, src)
}
func (m *JoinRoomR) XXX_Size() int {
	return xxx_messageInfo_JoinRoomR.Size(m)
}
func (m *JoinRoomR) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomR.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomR proto.InternalMessageInfo

func (m *JoinRoomR) GetCurBankers() []*UserInfo {
	if m != nil {
		return m.CurBankers
	}
	return nil
}

func (m *JoinRoomR) GetAmount() []float64 {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *JoinRoomR) GetPAmount() []float64 {
	if m != nil {
		return m.PAmount
	}
	return nil
}

func (m *JoinRoomR) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *JoinRoomR) GetHistory() []uint32 {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *JoinRoomR) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 下注
type Bet struct {
	Area                 uint32   `protobuf:"varint,1,opt,name=Area,proto3" json:"Area,omitempty"`
	Chip                 uint32   `protobuf:"varint,2,opt,name=Chip,proto3" json:"Chip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bet) Reset()         { *m = Bet{} }
func (m *Bet) String() string { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()    {}
func (*Bet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{11}
}

func (m *Bet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bet.Unmarshal(m, b)
}
func (m *Bet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bet.Marshal(b, m, deterministic)
}
func (m *Bet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bet.Merge(m, src)
}
func (m *Bet) XXX_Size() int {
	return xxx_messageInfo_Bet.Size(m)
}
func (m *Bet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bet.DiscardUnknown(m)
}

var xxx_messageInfo_Bet proto.InternalMessageInfo

func (m *Bet) GetArea() uint32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Bet) GetChip() uint32 {
	if m != nil {
		return m.Chip
	}
	return 0
}

// 进入房间后房间状态广播，比大厅广播更细粒度
// 包含了清理筹码倒计时，以及结算结果
// 状态枚举在 enum RoomStatus
type RoomStatusB struct {
	Status               uint32   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Counter              uint32   `protobuf:"varint,2,opt,name=Counter,proto3" json:"Counter,omitempty"`
	EndTime              uint32   `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Result               uint32   `protobuf:"varint,4,opt,name=Result,proto3" json:"Result,omitempty"`
	BankerWin            float64  `protobuf:"fixed64,5,opt,name=BankerWin,proto3" json:"BankerWin,omitempty"`
	WinMoney             float64  `protobuf:"fixed64,6,opt,name=WinMoney,proto3" json:"WinMoney,omitempty"`
	AutoBetAmount        float64  `protobuf:"fixed64,7,opt,name=AutoBetAmount,proto3" json:"AutoBetAmount,omitempty"`
	PlayerMoney          float64  `protobuf:"fixed64,8,opt,name=PlayerMoney,proto3" json:"PlayerMoney,omitempty"`
	ServerTime           uint32   `protobuf:"varint,9,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomStatusB) Reset()         { *m = RoomStatusB{} }
func (m *RoomStatusB) String() string { return proto.CompactTextString(m) }
func (*RoomStatusB) ProtoMessage()    {}
func (*RoomStatusB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{12}
}

func (m *RoomStatusB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomStatusB.Unmarshal(m, b)
}
func (m *RoomStatusB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomStatusB.Marshal(b, m, deterministic)
}
func (m *RoomStatusB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomStatusB.Merge(m, src)
}
func (m *RoomStatusB) XXX_Size() int {
	return xxx_messageInfo_RoomStatusB.Size(m)
}
func (m *RoomStatusB) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomStatusB.DiscardUnknown(m)
}

var xxx_messageInfo_RoomStatusB proto.InternalMessageInfo

func (m *RoomStatusB) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoomStatusB) GetCounter() uint32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *RoomStatusB) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoomStatusB) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RoomStatusB) GetBankerWin() float64 {
	if m != nil {
		return m.BankerWin
	}
	return 0
}

func (m *RoomStatusB) GetWinMoney() float64 {
	if m != nil {
		return m.WinMoney
	}
	return 0
}

func (m *RoomStatusB) GetAutoBetAmount() float64 {
	if m != nil {
		return m.AutoBetAmount
	}
	return 0
}

func (m *RoomStatusB) GetPlayerMoney() float64 {
	if m != nil {
		return m.PlayerMoney
	}
	return 0
}

func (m *RoomStatusB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 下注信息广播，收到投注请求即广播
type BetInfoB struct {
	Area                 uint32   `protobuf:"varint,1,opt,name=Area,proto3" json:"Area,omitempty"`
	Chip                 uint32   `protobuf:"varint,2,opt,name=Chip,proto3" json:"Chip,omitempty"`
	AreaTotal            float64  `protobuf:"fixed64,3,opt,name=AreaTotal,proto3" json:"AreaTotal,omitempty"`
	PlayerTotal          float64  `protobuf:"fixed64,4,opt,name=PlayerTotal,proto3" json:"PlayerTotal,omitempty"`
	PlayerID             uint32   `protobuf:"varint,5,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Money                float64  `protobuf:"fixed64,6,opt,name=Money,proto3" json:"Money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetInfoB) Reset()         { *m = BetInfoB{} }
func (m *BetInfoB) String() string { return proto.CompactTextString(m) }
func (*BetInfoB) ProtoMessage()    {}
func (*BetInfoB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{13}
}

func (m *BetInfoB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetInfoB.Unmarshal(m, b)
}
func (m *BetInfoB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetInfoB.Marshal(b, m, deterministic)
}
func (m *BetInfoB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetInfoB.Merge(m, src)
}
func (m *BetInfoB) XXX_Size() int {
	return xxx_messageInfo_BetInfoB.Size(m)
}
func (m *BetInfoB) XXX_DiscardUnknown() {
	xxx_messageInfo_BetInfoB.DiscardUnknown(m)
}

var xxx_messageInfo_BetInfoB proto.InternalMessageInfo

func (m *BetInfoB) GetArea() uint32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *BetInfoB) GetChip() uint32 {
	if m != nil {
		return m.Chip
	}
	return 0
}

func (m *BetInfoB) GetAreaTotal() float64 {
	if m != nil {
		return m.AreaTotal
	}
	return 0
}

func (m *BetInfoB) GetPlayerTotal() float64 {
	if m != nil {
		return m.PlayerTotal
	}
	return 0
}

func (m *BetInfoB) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *BetInfoB) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

// 庄家广播，数组第一个为当前庄家，若变化，则为庄家轮换
type BankersB struct {
	Banker               []*UserInfo `protobuf:"bytes,1,rep,name=Banker,proto3" json:"Banker,omitempty"`
	ServerTime           uint32      `protobuf:"varint,2,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BankersB) Reset()         { *m = BankersB{} }
func (m *BankersB) String() string { return proto.CompactTextString(m) }
func (*BankersB) ProtoMessage()    {}
func (*BankersB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{14}
}

func (m *BankersB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankersB.Unmarshal(m, b)
}
func (m *BankersB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankersB.Marshal(b, m, deterministic)
}
func (m *BankersB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankersB.Merge(m, src)
}
func (m *BankersB) XXX_Size() int {
	return xxx_messageInfo_BankersB.Size(m)
}
func (m *BankersB) XXX_DiscardUnknown() {
	xxx_messageInfo_BankersB.DiscardUnknown(m)
}

var xxx_messageInfo_BankersB proto.InternalMessageInfo

func (m *BankersB) GetBanker() []*UserInfo {
	if m != nil {
		return m.Banker
	}
	return nil
}

func (m *BankersB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 玩家列表请求
type Players struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Players) Reset()         { *m = Players{} }
func (m *Players) String() string { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()    {}
func (*Players) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{15}
}

func (m *Players) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Players.Unmarshal(m, b)
}
func (m *Players) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Players.Marshal(b, m, deterministic)
}
func (m *Players) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Players.Merge(m, src)
}
func (m *Players) XXX_Size() int {
	return xxx_messageInfo_Players.Size(m)
}
func (m *Players) XXX_DiscardUnknown() {
	xxx_messageInfo_Players.DiscardUnknown(m)
}

var xxx_messageInfo_Players proto.InternalMessageInfo

// 玩家列表返回
type PlayersR struct {
	Players              []*UserInfo `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
	ServerTime           uint32      `protobuf:"varint,2,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayersR) Reset()         { *m = PlayersR{} }
func (m *PlayersR) String() string { return proto.CompactTextString(m) }
func (*PlayersR) ProtoMessage()    {}
func (*PlayersR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{16}
}

func (m *PlayersR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersR.Unmarshal(m, b)
}
func (m *PlayersR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersR.Marshal(b, m, deterministic)
}
func (m *PlayersR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersR.Merge(m, src)
}
func (m *PlayersR) XXX_Size() int {
	return xxx_messageInfo_PlayersR.Size(m)
}
func (m *PlayersR) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersR.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersR proto.InternalMessageInfo

func (m *PlayersR) GetPlayers() []*UserInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *PlayersR) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 上庄
type GrabBanker struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrabBanker) Reset()         { *m = GrabBanker{} }
func (m *GrabBanker) String() string { return proto.CompactTextString(m) }
func (*GrabBanker) ProtoMessage()    {}
func (*GrabBanker) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{17}
}

func (m *GrabBanker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrabBanker.Unmarshal(m, b)
}
func (m *GrabBanker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrabBanker.Marshal(b, m, deterministic)
}
func (m *GrabBanker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrabBanker.Merge(m, src)
}
func (m *GrabBanker) XXX_Size() int {
	return xxx_messageInfo_GrabBanker.Size(m)
}
func (m *GrabBanker) XXX_DiscardUnknown() {
	xxx_messageInfo_GrabBanker.DiscardUnknown(m)
}

var xxx_messageInfo_GrabBanker proto.InternalMessageInfo

// 续投
type AutoBet struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoBet) Reset()         { *m = AutoBet{} }
func (m *AutoBet) String() string { return proto.CompactTextString(m) }
func (*AutoBet) ProtoMessage()    {}
func (*AutoBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{18}
}

func (m *AutoBet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoBet.Unmarshal(m, b)
}
func (m *AutoBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoBet.Marshal(b, m, deterministic)
}
func (m *AutoBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoBet.Merge(m, src)
}
func (m *AutoBet) XXX_Size() int {
	return xxx_messageInfo_AutoBet.Size(m)
}
func (m *AutoBet) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoBet.DiscardUnknown(m)
}

var xxx_messageInfo_AutoBet proto.InternalMessageInfo

type AutoBetR struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoBetR) Reset()         { *m = AutoBetR{} }
func (m *AutoBetR) String() string { return proto.CompactTextString(m) }
func (*AutoBetR) ProtoMessage()    {}
func (*AutoBetR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{19}
}

func (m *AutoBetR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoBetR.Unmarshal(m, b)
}
func (m *AutoBetR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoBetR.Marshal(b, m, deterministic)
}
func (m *AutoBetR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoBetR.Merge(m, src)
}
func (m *AutoBetR) XXX_Size() int {
	return xxx_messageInfo_AutoBetR.Size(m)
}
func (m *AutoBetR) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoBetR.DiscardUnknown(m)
}

var xxx_messageInfo_AutoBetR proto.InternalMessageInfo

// 离开房间
type LeaveRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom) Reset()         { *m = LeaveRoom{} }
func (m *LeaveRoom) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom) ProtoMessage()    {}
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{20}
}

func (m *LeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom.Unmarshal(m, b)
}
func (m *LeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom.Marshal(b, m, deterministic)
}
func (m *LeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom.Merge(m, src)
}
func (m *LeaveRoom) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom.Size(m)
}
func (m *LeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom proto.InternalMessageInfo

type LeaveRoomR struct {
	User                 *UserInfo   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	RoomID               uint32      `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Rooms                []*RoomInfo `protobuf:"bytes,3,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
	ServerTime           uint32      `protobuf:"varint,4,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LeaveRoomR) Reset()         { *m = LeaveRoomR{} }
func (m *LeaveRoomR) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomR) ProtoMessage()    {}
func (*LeaveRoomR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{21}
}

func (m *LeaveRoomR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomR.Unmarshal(m, b)
}
func (m *LeaveRoomR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomR.Marshal(b, m, deterministic)
}
func (m *LeaveRoomR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomR.Merge(m, src)
}
func (m *LeaveRoomR) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomR.Size(m)
}
func (m *LeaveRoomR) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomR.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomR proto.InternalMessageInfo

func (m *LeaveRoomR) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LeaveRoomR) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *LeaveRoomR) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *LeaveRoomR) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type Error struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=msg.ErrorCode" json:"Code,omitempty"`
	Detail               string    `protobuf:"bytes,2,opt,name=Detail,proto3" json:"Detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{22}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_Success
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("msg.AreaID", AreaID_name, AreaID_value)
	proto.RegisterEnum("msg.ChipID", ChipID_name, ChipID_value)
	proto.RegisterEnum("msg.RoomStatus", RoomStatus_name, RoomStatus_value)
	proto.RegisterEnum("msg.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Ping)(nil), "msg.Ping")
	proto.RegisterType((*Pong)(nil), "msg.Pong")
	proto.RegisterType((*UserInfo)(nil), "msg.UserInfo")
	proto.RegisterType((*RoomInfo)(nil), "msg.RoomInfo")
	proto.RegisterType((*Login)(nil), "msg.Login")
	proto.RegisterType((*LoginR)(nil), "msg.LoginR")
	proto.RegisterType((*RoomChangeHB)(nil), "msg.RoomChangeHB")
	proto.RegisterType((*Logout)(nil), "msg.Logout")
	proto.RegisterType((*LogoutR)(nil), "msg.LogoutR")
	proto.RegisterType((*JoinRoom)(nil), "msg.JoinRoom")
	proto.RegisterType((*JoinRoomR)(nil), "msg.JoinRoomR")
	proto.RegisterType((*Bet)(nil), "msg.Bet")
	proto.RegisterType((*RoomStatusB)(nil), "msg.RoomStatusB")
	proto.RegisterType((*BetInfoB)(nil), "msg.BetInfoB")
	proto.RegisterType((*BankersB)(nil), "msg.BankersB")
	proto.RegisterType((*Players)(nil), "msg.Players")
	proto.RegisterType((*PlayersR)(nil), "msg.PlayersR")
	proto.RegisterType((*GrabBanker)(nil), "msg.GrabBanker")
	proto.RegisterType((*AutoBet)(nil), "msg.AutoBet")
	proto.RegisterType((*AutoBetR)(nil), "msg.AutoBetR")
	proto.RegisterType((*LeaveRoom)(nil), "msg.LeaveRoom")
	proto.RegisterType((*LeaveRoomR)(nil), "msg.LeaveRoomR")
	proto.RegisterType((*Error)(nil), "msg.Error")
}

func init() { proto.RegisterFile("bcbm.proto", fileDescriptor_f920c4c0d180b49f) }

var fileDescriptor_f920c4c0d180b49f = []byte{
	// 1189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xde, 0x99, 0xb1, 0xc7, 0x33, 0xe5, 0x9f, 0x74, 0x7a, 0xa3, 0xc8, 0x5a, 0x01, 0xf2, 0x0e,
	0x20, 0xa2, 0x48, 0x1b, 0xe5, 0x67, 0xf7, 0xc4, 0x29, 0x76, 0x02, 0x31, 0x8a, 0xa3, 0x30, 0x59,
	0xb4, 0xc7, 0xd5, 0xc4, 0xe9, 0xcc, 0x8e, 0x62, 0x4f, 0x47, 0xd3, 0xed, 0xe0, 0xbc, 0x01, 0x07,
	0x38, 0x20, 0x5e, 0x01, 0x71, 0xe3, 0xe7, 0x35, 0x76, 0x79, 0x0c, 0x5e, 0x01, 0x89, 0x2b, 0xaa,
	0xee, 0x9e, 0x9f, 0xc4, 0x31, 0x70, 0xe3, 0xe4, 0xfa, 0xaa, 0xfa, 0xa7, 0xea, 0xfb, 0xaa, 0xcb,
	0x03, 0x70, 0x3e, 0x3e, 0x9f, 0x6e, 0x5d, 0x67, 0x5c, 0x72, 0xea, 0x4c, 0x45, 0x1c, 0xb8, 0x50,
	0x3b, 0x4d, 0x52, 0xfd, 0xcb, 0xd3, 0x38, 0xf8, 0xc9, 0x02, 0xef, 0x2b, 0xc1, 0xb2, 0x61, 0x7a,
	0xc9, 0xe9, 0x3a, 0xb8, 0xca, 0x3e, 0xe8, 0x5a, 0x3d, 0x6b, 0xa3, 0x1d, 0x1a, 0x44, 0xd7, 0xa0,
	0x3e, 0xe2, 0x29, 0xbb, 0xed, 0xda, 0x3d, 0x6b, 0xc3, 0x0a, 0x35, 0xc0, 0xd5, 0xfb, 0x37, 0x91,
	0x8c, 0xb2, 0xae, 0xd3, 0xb3, 0x36, 0xfc, 0xd0, 0x20, 0xfa, 0x04, 0xbc, 0x93, 0x64, 0x7c, 0x75,
	0x12, 0x4d, 0x59, 0xb7, 0xa6, 0x22, 0x05, 0xc6, 0xd8, 0xab, 0x24, 0x1d, 0xf0, 0x59, 0x2a, 0xbb,
	0xae, 0xba, 0xa3, 0xc0, 0xf4, 0x3d, 0xf0, 0xfb, 0x4c, 0xee, 0x4f, 0x55, 0xb0, 0xae, 0x6e, 0x2a,
	0x1d, 0xc1, 0x9f, 0x16, 0x78, 0x21, 0xe7, 0xd3, 0x3c, 0x51, 0x65, 0x17, 0x89, 0x6a, 0x84, 0xfe,
	0x51, 0x92, 0xf6, 0x99, 0x34, 0x99, 0x1a, 0xa4, 0xfc, 0xd1, 0x1c, 0xfd, 0x8e, 0xf1, 0x2b, 0x84,
	0xe9, 0x8c, 0x92, 0xf4, 0x38, 0x99, 0x26, 0x52, 0xa5, 0x6a, 0x85, 0x05, 0xc6, 0x3d, 0x67, 0x32,
	0x92, 0x33, 0xa1, 0x72, 0x69, 0x87, 0x06, 0xd1, 0x2e, 0x34, 0x54, 0xbe, 0x2c, 0x33, 0x15, 0xe4,
	0x10, 0x23, 0x87, 0xe9, 0xc5, 0xcb, 0x64, 0xca, 0xba, 0x0d, 0x1d, 0x31, 0x10, 0x23, 0x47, 0x89,
	0x90, 0x3c, 0xbb, 0xed, 0x7a, 0x3d, 0x07, 0x23, 0x06, 0xd2, 0x0f, 0x00, 0xf0, 0xdc, 0x44, 0xc8,
	0x64, 0x2c, 0xba, 0xbe, 0x0a, 0x56, 0x3c, 0xc1, 0xa7, 0x50, 0x3f, 0xe6, 0x71, 0x92, 0x2e, 0xd5,
	0xe6, 0x09, 0x78, 0xa7, 0x91, 0x10, 0x5f, 0xf3, 0xec, 0x42, 0x15, 0xed, 0x87, 0x05, 0x0e, 0xbe,
	0xb1, 0xc0, 0x55, 0xbb, 0x43, 0xfa, 0x14, 0x6a, 0xb8, 0x41, 0x6d, 0x6e, 0xee, 0xb6, 0xb7, 0xa6,
	0x22, 0xde, 0xca, 0x75, 0x0f, 0x55, 0xa8, 0x42, 0xaa, 0x7d, 0x87, 0xd4, 0x0f, 0xa1, 0x8e, 0x96,
	0xe8, 0x3a, 0x3d, 0xa7, 0xd8, 0x9b, 0x4b, 0x11, 0xea, 0x98, 0xaa, 0x83, 0x65, 0x37, 0x2c, 0x53,
	0xe5, 0xd7, 0xd4, 0x01, 0x15, 0x4f, 0xf0, 0xce, 0x82, 0x16, 0xae, 0x1c, 0xbc, 0x89, 0xd2, 0x98,
	0x1d, 0xf5, 0xff, 0x49, 0x42, 0x43, 0xbb, 0xbd, 0x8c, 0x76, 0x67, 0x29, 0xed, 0xb5, 0xbb, 0xb4,
	0xe3, 0x1d, 0x4c, 0xcc, 0x26, 0x32, 0x97, 0x50, 0xa3, 0x7b, 0xa4, 0xbb, 0xf7, 0x49, 0xbf, 0x57,
	0x4c, 0x63, 0xa1, 0x18, 0x4f, 0xd1, 0xca, 0x67, 0x32, 0xf0, 0xa1, 0xa1, 0xad, 0x30, 0x08, 0xc0,
	0xfb, 0x82, 0x27, 0x29, 0x96, 0xb1, 0xac, 0xb8, 0xe0, 0xad, 0x05, 0x7e, 0xbe, 0x28, 0xa4, 0xcf,
	0x00, 0x06, 0xb3, 0xac, 0x1f, 0xa5, 0x57, 0x2c, 0x13, 0x5d, 0xab, 0xc2, 0x6e, 0xa1, 0x4c, 0x65,
	0x81, 0x7a, 0x6f, 0xfa, 0x71, 0xd8, 0x3d, 0x07, 0x9b, 0x58, 0x23, 0xac, 0xff, 0xd4, 0x04, 0x1c,
	0x15, 0xc8, 0x21, 0x8a, 0x8e, 0x37, 0x29, 0x5a, 0x16, 0x84, 0x53, 0xa1, 0x6a, 0x67, 0xd6, 0x17,
	0x3b, 0xb3, 0x24, 0xc1, 0x5d, 0x20, 0xe1, 0x19, 0x38, 0xf8, 0x84, 0x28, 0xd4, 0xf6, 0x33, 0x16,
	0x99, 0x42, 0x95, 0x8d, 0xbe, 0xc1, 0x9b, 0xe4, 0xda, 0x28, 0xa8, 0xec, 0xe0, 0x07, 0x1b, 0x9a,
	0x78, 0xa3, 0x96, 0xb3, 0x5f, 0xd1, 0xd9, 0x5a, 0xa6, 0xb3, 0xbd, 0x54, 0x67, 0x67, 0x99, 0xce,
	0xb5, 0x3b, 0x3a, 0xe3, 0x44, 0x51, 0xe4, 0xbd, 0x4a, 0xd2, 0x62, 0xa2, 0xe4, 0x0e, 0x33, 0x8b,
	0xf4, 0x60, 0x73, 0xf5, 0xe3, 0xcf, 0x31, 0xfd, 0x08, 0xda, 0xfb, 0x33, 0xc9, 0xcb, 0x79, 0xd4,
	0x50, 0x0b, 0xee, 0x3a, 0x69, 0x0f, 0x9a, 0xa7, 0x93, 0xe8, 0x96, 0x65, 0xfa, 0x10, 0x4f, 0xad,
	0xa9, 0xba, 0xee, 0x91, 0xe8, 0x2f, 0x90, 0xf8, 0xa3, 0x05, 0x5e, 0x9f, 0x49, 0x14, 0xa4, 0xff,
	0x5f, 0xa9, 0xc4, 0xb2, 0x30, 0xf6, 0x92, 0xcb, 0x68, 0x62, 0x06, 0x5a, 0xe9, 0x28, 0x93, 0xd2,
	0xf1, 0x5a, 0x35, 0x29, 0xbd, 0x02, 0x47, 0x86, 0x82, 0xc3, 0x03, 0xf3, 0x30, 0x0a, 0x5c, 0x8e,
	0x7a, 0xb7, 0x32, 0xea, 0x83, 0x2f, 0xc1, 0x33, 0x5d, 0xd8, 0xa7, 0x1f, 0x83, 0xab, 0xed, 0x87,
	0x3b, 0xd6, 0x04, 0xef, 0x55, 0x6e, 0x2f, 0x54, 0xee, 0x43, 0x43, 0x5f, 0x2a, 0x82, 0xb3, 0x3c,
	0x1f, 0x11, 0xd2, 0x4f, 0x0a, 0xf7, 0xc3, 0xc7, 0xe7, 0xd1, 0x7f, 0x3d, 0xbf, 0x05, 0xf0, 0x79,
	0x16, 0x9d, 0xeb, 0x6c, 0xf0, 0x36, 0x23, 0x5d, 0x00, 0xe0, 0x19, 0x33, 0x0c, 0x9a, 0xe0, 0x1f,
	0xb3, 0xe8, 0x86, 0x61, 0x63, 0x06, 0xdf, 0x5a, 0x00, 0x05, 0xfa, 0xff, 0x27, 0xe6, 0x00, 0xea,
	0x87, 0x59, 0xc6, 0x33, 0x1a, 0x40, 0x6d, 0xc0, 0x2f, 0x98, 0x4a, 0xa4, 0xb3, 0xdb, 0x51, 0x87,
	0xa9, 0x08, 0x7a, 0x43, 0x15, 0xc3, 0x4c, 0x0e, 0x98, 0x8c, 0x92, 0x89, 0xf9, 0x0f, 0x30, 0x68,
	0xf3, 0x0f, 0x1b, 0xfc, 0x11, 0x13, 0x22, 0x8a, 0xd9, 0xf0, 0x80, 0xb6, 0xc0, 0x1b, 0x89, 0x58,
	0xed, 0x25, 0x8f, 0x68, 0x13, 0x1a, 0x23, 0x11, 0xe3, 0xd7, 0x00, 0xb1, 0x72, 0xc0, 0xd3, 0x98,
	0xd8, 0x66, 0x9d, 0xfa, 0xe7, 0x20, 0x0e, 0x6d, 0x83, 0x9f, 0xa3, 0x90, 0xd4, 0x4a, 0xc8, 0x67,
	0x92, 0xd4, 0x69, 0x07, 0xa0, 0x80, 0x21, 0x71, 0xe9, 0x63, 0x58, 0x19, 0x89, 0xb8, 0x3a, 0xea,
	0x49, 0x83, 0xae, 0x40, 0x73, 0x24, 0xe2, 0x7c, 0xf2, 0x11, 0x8f, 0x12, 0x68, 0x55, 0x1c, 0x21,
	0xf1, 0x8d, 0xa7, 0xe0, 0x9f, 0x00, 0x5d, 0x85, 0x76, 0xd5, 0x13, 0x92, 0xa6, 0x71, 0x95, 0xba,
	0x92, 0x96, 0xb9, 0xdf, 0x28, 0x4a, 0xda, 0xe6, 0xaa, 0x5c, 0x61, 0xd2, 0xa1, 0x00, 0xee, 0x48,
	0xc4, 0x18, 0x5c, 0x31, 0xc1, 0xfc, 0xc1, 0x11, 0x92, 0x3b, 0x4c, 0x6f, 0x93, 0x55, 0x73, 0x9c,
	0x69, 0x32, 0x42, 0xcd, 0x82, 0xbc, 0x3d, 0xc9, 0x63, 0x4a, 0xa1, 0x63, 0xea, 0x33, 0x93, 0x8c,
	0xac, 0x6d, 0x7e, 0x67, 0x81, 0x8b, 0x0f, 0x70, 0x78, 0x80, 0x3c, 0xbe, 0xd6, 0x26, 0x79, 0x84,
	0x54, 0x69, 0xfb, 0xf9, 0xf6, 0x9c, 0x58, 0x25, 0xdc, 0xdb, 0x9e, 0x13, 0xbb, 0x84, 0xbb, 0xdb,
	0x73, 0x4d, 0xb3, 0x86, 0x3b, 0xdb, 0x73, 0x4d, 0xb3, 0x86, 0x2f, 0xe6, 0x3b, 0xa4, 0x5e, 0x85,
	0xbb, 0xc4, 0xad, 0xc2, 0x3d, 0xd2, 0xa8, 0xc2, 0xe7, 0xc4, 0xdb, 0x8c, 0xc0, 0xc5, 0x41, 0x61,
	0xd2, 0xd1, 0x26, 0x79, 0x84, 0xb2, 0x6a, 0x7b, 0xc7, 0x64, 0x63, 0x90, 0xca, 0xa6, 0x03, 0x90,
	0x43, 0x95, 0x4e, 0x81, 0x5f, 0x6c, 0xe7, 0xf9, 0x98, 0xf8, 0xd5, 0x9c, 0xd4, 0x37, 0x8f, 0x00,
	0x4a, 0x0e, 0x90, 0xa5, 0xd7, 0x25, 0xd4, 0x95, 0x87, 0x67, 0x7d, 0x26, 0xa5, 0xee, 0x2e, 0x05,
	0x8f, 0xb9, 0x94, 0x2c, 0xbb, 0x25, 0x36, 0x66, 0x15, 0x9e, 0x0d, 0x26, 0x2c, 0xca, 0x88, 0xb3,
	0xf9, 0x97, 0x05, 0x7e, 0xd1, 0xce, 0x18, 0x3a, 0x9b, 0x8d, 0xc7, 0x4c, 0xe0, 0x29, 0x4f, 0xe1,
	0xfd, 0x61, 0x2a, 0x66, 0x97, 0x97, 0xc9, 0x38, 0x61, 0xa9, 0xec, 0x47, 0x93, 0x28, 0x1d, 0xb3,
	0x8a, 0xfc, 0xf8, 0x41, 0xb9, 0xfe, 0xc0, 0x12, 0x54, 0xfb, 0x92, 0xae, 0x42, 0x4b, 0xbf, 0xa7,
	0xc1, 0x84, 0x0b, 0x76, 0x41, 0xde, 0x5a, 0x74, 0x0d, 0x56, 0xf0, 0xe5, 0x86, 0xec, 0x9a, 0x45,
	0x52, 0x37, 0xf8, 0xbb, 0x8a, 0x77, 0xca, 0x25, 0xd3, 0xde, 0xdf, 0x2d, 0x4a, 0xa1, 0x8d, 0xde,
	0x13, 0x2e, 0x87, 0xba, 0x6d, 0x7f, 0xb6, 0xe9, 0x3a, 0xac, 0xa2, 0x6f, 0x7f, 0x92, 0xb1, 0xe8,
	0xe2, 0xd6, 0xf8, 0x7f, 0xb1, 0xf1, 0x2a, 0x34, 0x4f, 0xb8, 0x3c, 0x9c, 0x27, 0x42, 0x92, 0x5f,
	0x51, 0x5e, 0xf5, 0xbd, 0xfa, 0xd9, 0x6c, 0x32, 0x21, 0xbf, 0xa9, 0x15, 0xea, 0xa4, 0x9c, 0x94,
	0xef, 0x9d, 0x73, 0x57, 0x7d, 0x97, 0xef, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x89, 0x7a,
	0xdb, 0xa5, 0x0b, 0x00, 0x00,
}
