// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bcbm.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageID int32

const (
	MessageID_MsgError      MessageID = 0
	MessageID_MsgPing       MessageID = 1
	MessageID_MsgPong       MessageID = 2
	MessageID_MsgLoginTest  MessageID = 3
	MessageID_MsgLogin      MessageID = 4
	MessageID_MsgLoginR     MessageID = 5
	MessageID_MsgLogout     MessageID = 6
	MessageID_MsgLogoutR    MessageID = 7
	MessageID_MsgJoinRoom   MessageID = 8
	MessageID_MsgJoinRoomR  MessageID = 9
	MessageID_MsgLeaveRoom  MessageID = 10
	MessageID_MsgLeaveRoomR MessageID = 11
	MessageID_MsgGrabBanker MessageID = 12
	MessageID_MsgAutoBet    MessageID = 13
	MessageID_MsgAutoBetR   MessageID = 14
	MessageID_MsgBet        MessageID = 15
	MessageID_MsgBetR       MessageID = 16
	MessageID_MsgBetInfoB   MessageID = 17
	MessageID_MsgBankersB   MessageID = 18
	MessageID_MsgPlayersB   MessageID = 19
)

var MessageID_name = map[int32]string{
	0:  "MsgError",
	1:  "MsgPing",
	2:  "MsgPong",
	3:  "MsgLoginTest",
	4:  "MsgLogin",
	5:  "MsgLoginR",
	6:  "MsgLogout",
	7:  "MsgLogoutR",
	8:  "MsgJoinRoom",
	9:  "MsgJoinRoomR",
	10: "MsgLeaveRoom",
	11: "MsgLeaveRoomR",
	12: "MsgGrabBanker",
	13: "MsgAutoBet",
	14: "MsgAutoBetR",
	15: "MsgBet",
	16: "MsgBetR",
	17: "MsgBetInfoB",
	18: "MsgBankersB",
	19: "MsgPlayersB",
}

var MessageID_value = map[string]int32{
	"MsgError":      0,
	"MsgPing":       1,
	"MsgPong":       2,
	"MsgLoginTest":  3,
	"MsgLogin":      4,
	"MsgLoginR":     5,
	"MsgLogout":     6,
	"MsgLogoutR":    7,
	"MsgJoinRoom":   8,
	"MsgJoinRoomR":  9,
	"MsgLeaveRoom":  10,
	"MsgLeaveRoomR": 11,
	"MsgGrabBanker": 12,
	"MsgAutoBet":    13,
	"MsgAutoBetR":   14,
	"MsgBet":        15,
	"MsgBetR":       16,
	"MsgBetInfoB":   17,
	"MsgBankersB":   18,
	"MsgPlayersB":   19,
}

func (x MessageID) String() string {
	return proto.EnumName(MessageID_name, int32(x))
}

func (MessageID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_Success                       ErrorCode = 0
	ErrorCode_InsufficientBalanceGrabDealer ErrorCode = 101
	ErrorCode_InsufficientBalanceBet        ErrorCode = 102
	ErrorCode_ServerClosed                  ErrorCode = 201
	ErrorCode_UserRepeatLogin               ErrorCode = 202
	ErrorCode_UserRemoteLogin               ErrorCode = 203
)

var ErrorCode_name = map[int32]string{
	0:   "Success",
	101: "InsufficientBalanceGrabDealer",
	102: "InsufficientBalanceBet",
	201: "ServerClosed",
	202: "UserRepeatLogin",
	203: "UserRemoteLogin",
}

var ErrorCode_value = map[string]int32{
	"Success":                       0,
	"InsufficientBalanceGrabDealer": 101,
	"InsufficientBalanceBet":        102,
	"ServerClosed":                  201,
	"UserRepeatLogin":               202,
	"UserRemoteLogin":               203,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{1}
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type UserInfo struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Money                float64  `protobuf:"fixed64,2,opt,name=Money,proto3" json:"Money,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	BetAmount            float64  `protobuf:"fixed64,5,opt,name=BetAmount,proto3" json:"BetAmount,omitempty"`
	WinCount             uint32   `protobuf:"varint,6,opt,name=WinCount,proto3" json:"WinCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserInfo) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *UserInfo) GetBetAmount() float64 {
	if m != nil {
		return m.BetAmount
	}
	return 0
}

func (m *UserInfo) GetWinCount() uint32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

type RoomInfo struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	MinBet               uint32   `protobuf:"varint,2,opt,name=MinBet,proto3" json:"MinBet,omitempty"`
	MaxBet               uint32   `protobuf:"varint,3,opt,name=MaxBet,proto3" json:"MaxBet,omitempty"`
	MinLimit             uint32   `protobuf:"varint,4,opt,name=MinLimit,proto3" json:"MinLimit,omitempty"`
	Status               uint32   `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	EndTime              uint32   `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	History              []uint32 `protobuf:"varint,7,rep,packed,name=History,proto3" json:"History,omitempty"`
	HisStatistic         []uint32 `protobuf:"varint,8,rep,packed,name=HisStatistic,proto3" json:"HisStatistic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{3}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomInfo) GetMinBet() uint32 {
	if m != nil {
		return m.MinBet
	}
	return 0
}

func (m *RoomInfo) GetMaxBet() uint32 {
	if m != nil {
		return m.MaxBet
	}
	return 0
}

func (m *RoomInfo) GetMinLimit() uint32 {
	if m != nil {
		return m.MinLimit
	}
	return 0
}

func (m *RoomInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoomInfo) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoomInfo) GetHistory() []uint32 {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *RoomInfo) GetHisStatistic() []uint32 {
	if m != nil {
		return m.HisStatistic
	}
	return nil
}

type RoomChangeHB struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Status               uint32   `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	EndTime              uint32   `protobuf:"varint,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Result               uint32   `protobuf:"varint,4,opt,name=Result,proto3" json:"Result,omitempty"`
	ServerTime           uint32   `protobuf:"varint,5,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomChangeHB) Reset()         { *m = RoomChangeHB{} }
func (m *RoomChangeHB) String() string { return proto.CompactTextString(m) }
func (*RoomChangeHB) ProtoMessage()    {}
func (*RoomChangeHB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{4}
}

func (m *RoomChangeHB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomChangeHB.Unmarshal(m, b)
}
func (m *RoomChangeHB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomChangeHB.Marshal(b, m, deterministic)
}
func (m *RoomChangeHB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomChangeHB.Merge(m, src)
}
func (m *RoomChangeHB) XXX_Size() int {
	return xxx_messageInfo_RoomChangeHB.Size(m)
}
func (m *RoomChangeHB) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomChangeHB.DiscardUnknown(m)
}

var xxx_messageInfo_RoomChangeHB proto.InternalMessageInfo

func (m *RoomChangeHB) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *RoomChangeHB) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RoomChangeHB) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *RoomChangeHB) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RoomChangeHB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type BetInfoB struct {
	AmountBenzGolden     float64  `protobuf:"fixed64,1,opt,name=AmountBenzGolden,proto3" json:"AmountBenzGolden,omitempty"`
	AmountBenz           float64  `protobuf:"fixed64,2,opt,name=AmountBenz,proto3" json:"AmountBenz,omitempty"`
	AmountBMWGolden      float64  `protobuf:"fixed64,3,opt,name=AmountBMWGolden,proto3" json:"AmountBMWGolden,omitempty"`
	AmountBMW            float64  `protobuf:"fixed64,4,opt,name=AmountBMW,proto3" json:"AmountBMW,omitempty"`
	AmountAudiGolden     float64  `protobuf:"fixed64,5,opt,name=AmountAudiGolden,proto3" json:"AmountAudiGolden,omitempty"`
	AmountAudi           float64  `protobuf:"fixed64,6,opt,name=AmountAudi,proto3" json:"AmountAudi,omitempty"`
	AmountVWGolden       float64  `protobuf:"fixed64,7,opt,name=AmountVWGolden,proto3" json:"AmountVWGolden,omitempty"`
	AmountVW             float64  `protobuf:"fixed64,8,opt,name=AmountVW,proto3" json:"AmountVW,omitempty"`
	ServerTime           uint32   `protobuf:"varint,9,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetInfoB) Reset()         { *m = BetInfoB{} }
func (m *BetInfoB) String() string { return proto.CompactTextString(m) }
func (*BetInfoB) ProtoMessage()    {}
func (*BetInfoB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{5}
}

func (m *BetInfoB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetInfoB.Unmarshal(m, b)
}
func (m *BetInfoB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetInfoB.Marshal(b, m, deterministic)
}
func (m *BetInfoB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetInfoB.Merge(m, src)
}
func (m *BetInfoB) XXX_Size() int {
	return xxx_messageInfo_BetInfoB.Size(m)
}
func (m *BetInfoB) XXX_DiscardUnknown() {
	xxx_messageInfo_BetInfoB.DiscardUnknown(m)
}

var xxx_messageInfo_BetInfoB proto.InternalMessageInfo

func (m *BetInfoB) GetAmountBenzGolden() float64 {
	if m != nil {
		return m.AmountBenzGolden
	}
	return 0
}

func (m *BetInfoB) GetAmountBenz() float64 {
	if m != nil {
		return m.AmountBenz
	}
	return 0
}

func (m *BetInfoB) GetAmountBMWGolden() float64 {
	if m != nil {
		return m.AmountBMWGolden
	}
	return 0
}

func (m *BetInfoB) GetAmountBMW() float64 {
	if m != nil {
		return m.AmountBMW
	}
	return 0
}

func (m *BetInfoB) GetAmountAudiGolden() float64 {
	if m != nil {
		return m.AmountAudiGolden
	}
	return 0
}

func (m *BetInfoB) GetAmountAudi() float64 {
	if m != nil {
		return m.AmountAudi
	}
	return 0
}

func (m *BetInfoB) GetAmountVWGolden() float64 {
	if m != nil {
		return m.AmountVWGolden
	}
	return 0
}

func (m *BetInfoB) GetAmountVW() float64 {
	if m != nil {
		return m.AmountVW
	}
	return 0
}

func (m *BetInfoB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type BankersB struct {
	Dealer               []*UserInfo `protobuf:"bytes,1,rep,name=Dealer,proto3" json:"Dealer,omitempty"`
	ServerTime           uint32      `protobuf:"varint,2,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BankersB) Reset()         { *m = BankersB{} }
func (m *BankersB) String() string { return proto.CompactTextString(m) }
func (*BankersB) ProtoMessage()    {}
func (*BankersB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{6}
}

func (m *BankersB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankersB.Unmarshal(m, b)
}
func (m *BankersB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankersB.Marshal(b, m, deterministic)
}
func (m *BankersB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankersB.Merge(m, src)
}
func (m *BankersB) XXX_Size() int {
	return xxx_messageInfo_BankersB.Size(m)
}
func (m *BankersB) XXX_DiscardUnknown() {
	xxx_messageInfo_BankersB.DiscardUnknown(m)
}

var xxx_messageInfo_BankersB proto.InternalMessageInfo

func (m *BankersB) GetDealer() []*UserInfo {
	if m != nil {
		return m.Dealer
	}
	return nil
}

func (m *BankersB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type PlayersB struct {
	Players              []*UserInfo `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
	ServerTime           uint32      `protobuf:"varint,2,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlayersB) Reset()         { *m = PlayersB{} }
func (m *PlayersB) String() string { return proto.CompactTextString(m) }
func (*PlayersB) ProtoMessage()    {}
func (*PlayersB) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{7}
}

func (m *PlayersB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersB.Unmarshal(m, b)
}
func (m *PlayersB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersB.Marshal(b, m, deterministic)
}
func (m *PlayersB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersB.Merge(m, src)
}
func (m *PlayersB) XXX_Size() int {
	return xxx_messageInfo_PlayersB.Size(m)
}
func (m *PlayersB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersB.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersB proto.InternalMessageInfo

func (m *PlayersB) GetPlayers() []*UserInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *PlayersB) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type Login struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{8}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginTest struct {
	UserID               uint32   `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginTest) Reset()         { *m = LoginTest{} }
func (m *LoginTest) String() string { return proto.CompactTextString(m) }
func (*LoginTest) ProtoMessage()    {}
func (*LoginTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{9}
}

func (m *LoginTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginTest.Unmarshal(m, b)
}
func (m *LoginTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginTest.Marshal(b, m, deterministic)
}
func (m *LoginTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginTest.Merge(m, src)
}
func (m *LoginTest) XXX_Size() int {
	return xxx_messageInfo_LoginTest.Size(m)
}
func (m *LoginTest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginTest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginTest proto.InternalMessageInfo

func (m *LoginTest) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type LoginR struct {
	User                 *UserInfo   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	RoomID               uint32      `protobuf:"varint,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Rooms                []*RoomInfo `protobuf:"bytes,3,rep,name=Rooms,proto3" json:"Rooms,omitempty"`
	ServerTime           uint32      `protobuf:"varint,4,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginR) Reset()         { *m = LoginR{} }
func (m *LoginR) String() string { return proto.CompactTextString(m) }
func (*LoginR) ProtoMessage()    {}
func (*LoginR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{10}
}

func (m *LoginR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginR.Unmarshal(m, b)
}
func (m *LoginR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginR.Marshal(b, m, deterministic)
}
func (m *LoginR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginR.Merge(m, src)
}
func (m *LoginR) XXX_Size() int {
	return xxx_messageInfo_LoginR.Size(m)
}
func (m *LoginR) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginR.DiscardUnknown(m)
}

var xxx_messageInfo_LoginR proto.InternalMessageInfo

func (m *LoginR) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginR) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *LoginR) GetRooms() []*RoomInfo {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *LoginR) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type Logout struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout) Reset()         { *m = Logout{} }
func (m *Logout) String() string { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()    {}
func (*Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{11}
}

func (m *Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout.Unmarshal(m, b)
}
func (m *Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout.Marshal(b, m, deterministic)
}
func (m *Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout.Merge(m, src)
}
func (m *Logout) XXX_Size() int {
	return xxx_messageInfo_Logout.Size(m)
}
func (m *Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Logout proto.InternalMessageInfo

type LogoutR struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutR) Reset()         { *m = LogoutR{} }
func (m *LogoutR) String() string { return proto.CompactTextString(m) }
func (*LogoutR) ProtoMessage()    {}
func (*LogoutR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{12}
}

func (m *LogoutR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutR.Unmarshal(m, b)
}
func (m *LogoutR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutR.Marshal(b, m, deterministic)
}
func (m *LogoutR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutR.Merge(m, src)
}
func (m *LogoutR) XXX_Size() int {
	return xxx_messageInfo_LogoutR.Size(m)
}
func (m *LogoutR) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutR.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutR proto.InternalMessageInfo

type JoinRoom struct {
	RoomID               uint32   `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom) Reset()         { *m = JoinRoom{} }
func (m *JoinRoom) String() string { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()    {}
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{13}
}

func (m *JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom.Unmarshal(m, b)
}
func (m *JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom.Marshal(b, m, deterministic)
}
func (m *JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom.Merge(m, src)
}
func (m *JoinRoom) XXX_Size() int {
	return xxx_messageInfo_JoinRoom.Size(m)
}
func (m *JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom proto.InternalMessageInfo

func (m *JoinRoom) GetRoomID() uint32 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

type JoinRoomR struct {
	CurDealers           *UserInfo   `protobuf:"bytes,1,opt,name=CurDealers,proto3" json:"CurDealers,omitempty"`
	CurBetInfo           *BetInfoB   `protobuf:"bytes,2,opt,name=CurBetInfo,proto3" json:"CurBetInfo,omitempty"`
	Players              []*UserInfo `protobuf:"bytes,3,rep,name=Players,proto3" json:"Players,omitempty"`
	ServerTime           uint32      `protobuf:"varint,4,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomR) Reset()         { *m = JoinRoomR{} }
func (m *JoinRoomR) String() string { return proto.CompactTextString(m) }
func (*JoinRoomR) ProtoMessage()    {}
func (*JoinRoomR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{14}
}

func (m *JoinRoomR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomR.Unmarshal(m, b)
}
func (m *JoinRoomR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomR.Marshal(b, m, deterministic)
}
func (m *JoinRoomR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomR.Merge(m, src)
}
func (m *JoinRoomR) XXX_Size() int {
	return xxx_messageInfo_JoinRoomR.Size(m)
}
func (m *JoinRoomR) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomR.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomR proto.InternalMessageInfo

func (m *JoinRoomR) GetCurDealers() *UserInfo {
	if m != nil {
		return m.CurDealers
	}
	return nil
}

func (m *JoinRoomR) GetCurBetInfo() *BetInfoB {
	if m != nil {
		return m.CurBetInfo
	}
	return nil
}

func (m *JoinRoomR) GetPlayers() []*UserInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *JoinRoomR) GetServerTime() uint32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type LeaveRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoom) Reset()         { *m = LeaveRoom{} }
func (m *LeaveRoom) String() string { return proto.CompactTextString(m) }
func (*LeaveRoom) ProtoMessage()    {}
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{15}
}

func (m *LeaveRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoom.Unmarshal(m, b)
}
func (m *LeaveRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoom.Marshal(b, m, deterministic)
}
func (m *LeaveRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoom.Merge(m, src)
}
func (m *LeaveRoom) XXX_Size() int {
	return xxx_messageInfo_LeaveRoom.Size(m)
}
func (m *LeaveRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoom.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoom proto.InternalMessageInfo

type LeaveRoomR struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomR) Reset()         { *m = LeaveRoomR{} }
func (m *LeaveRoomR) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomR) ProtoMessage()    {}
func (*LeaveRoomR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{16}
}

func (m *LeaveRoomR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomR.Unmarshal(m, b)
}
func (m *LeaveRoomR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomR.Marshal(b, m, deterministic)
}
func (m *LeaveRoomR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomR.Merge(m, src)
}
func (m *LeaveRoomR) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomR.Size(m)
}
func (m *LeaveRoomR) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomR.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomR proto.InternalMessageInfo

type GrabBanker struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrabBanker) Reset()         { *m = GrabBanker{} }
func (m *GrabBanker) String() string { return proto.CompactTextString(m) }
func (*GrabBanker) ProtoMessage()    {}
func (*GrabBanker) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{17}
}

func (m *GrabBanker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrabBanker.Unmarshal(m, b)
}
func (m *GrabBanker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrabBanker.Marshal(b, m, deterministic)
}
func (m *GrabBanker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrabBanker.Merge(m, src)
}
func (m *GrabBanker) XXX_Size() int {
	return xxx_messageInfo_GrabBanker.Size(m)
}
func (m *GrabBanker) XXX_DiscardUnknown() {
	xxx_messageInfo_GrabBanker.DiscardUnknown(m)
}

var xxx_messageInfo_GrabBanker proto.InternalMessageInfo

type Bet struct {
	Area                 uint32   `protobuf:"varint,1,opt,name=Area,proto3" json:"Area,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bet) Reset()         { *m = Bet{} }
func (m *Bet) String() string { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()    {}
func (*Bet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{18}
}

func (m *Bet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bet.Unmarshal(m, b)
}
func (m *Bet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bet.Marshal(b, m, deterministic)
}
func (m *Bet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bet.Merge(m, src)
}
func (m *Bet) XXX_Size() int {
	return xxx_messageInfo_Bet.Size(m)
}
func (m *Bet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bet.DiscardUnknown(m)
}

var xxx_messageInfo_Bet proto.InternalMessageInfo

func (m *Bet) GetArea() uint32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Bet) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type BetR struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BetR) Reset()         { *m = BetR{} }
func (m *BetR) String() string { return proto.CompactTextString(m) }
func (*BetR) ProtoMessage()    {}
func (*BetR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{19}
}

func (m *BetR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BetR.Unmarshal(m, b)
}
func (m *BetR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BetR.Marshal(b, m, deterministic)
}
func (m *BetR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BetR.Merge(m, src)
}
func (m *BetR) XXX_Size() int {
	return xxx_messageInfo_BetR.Size(m)
}
func (m *BetR) XXX_DiscardUnknown() {
	xxx_messageInfo_BetR.DiscardUnknown(m)
}

var xxx_messageInfo_BetR proto.InternalMessageInfo

type AutoBet struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoBet) Reset()         { *m = AutoBet{} }
func (m *AutoBet) String() string { return proto.CompactTextString(m) }
func (*AutoBet) ProtoMessage()    {}
func (*AutoBet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{20}
}

func (m *AutoBet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoBet.Unmarshal(m, b)
}
func (m *AutoBet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoBet.Marshal(b, m, deterministic)
}
func (m *AutoBet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoBet.Merge(m, src)
}
func (m *AutoBet) XXX_Size() int {
	return xxx_messageInfo_AutoBet.Size(m)
}
func (m *AutoBet) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoBet.DiscardUnknown(m)
}

var xxx_messageInfo_AutoBet proto.InternalMessageInfo

type AutoBetR struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoBetR) Reset()         { *m = AutoBetR{} }
func (m *AutoBetR) String() string { return proto.CompactTextString(m) }
func (*AutoBetR) ProtoMessage()    {}
func (*AutoBetR) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{21}
}

func (m *AutoBetR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoBetR.Unmarshal(m, b)
}
func (m *AutoBetR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoBetR.Marshal(b, m, deterministic)
}
func (m *AutoBetR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoBetR.Merge(m, src)
}
func (m *AutoBetR) XXX_Size() int {
	return xxx_messageInfo_AutoBetR.Size(m)
}
func (m *AutoBetR) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoBetR.DiscardUnknown(m)
}

var xxx_messageInfo_AutoBetR proto.InternalMessageInfo

type Error struct {
	Code                 ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=msg.ErrorCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f920c4c0d180b49f, []int{22}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_Success
}

func init() {
	proto.RegisterEnum("msg.MessageID", MessageID_name, MessageID_value)
	proto.RegisterEnum("msg.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Ping)(nil), "msg.Ping")
	proto.RegisterType((*Pong)(nil), "msg.Pong")
	proto.RegisterType((*UserInfo)(nil), "msg.UserInfo")
	proto.RegisterType((*RoomInfo)(nil), "msg.RoomInfo")
	proto.RegisterType((*RoomChangeHB)(nil), "msg.RoomChangeHB")
	proto.RegisterType((*BetInfoB)(nil), "msg.BetInfoB")
	proto.RegisterType((*BankersB)(nil), "msg.BankersB")
	proto.RegisterType((*PlayersB)(nil), "msg.PlayersB")
	proto.RegisterType((*Login)(nil), "msg.Login")
	proto.RegisterType((*LoginTest)(nil), "msg.LoginTest")
	proto.RegisterType((*LoginR)(nil), "msg.LoginR")
	proto.RegisterType((*Logout)(nil), "msg.Logout")
	proto.RegisterType((*LogoutR)(nil), "msg.LogoutR")
	proto.RegisterType((*JoinRoom)(nil), "msg.JoinRoom")
	proto.RegisterType((*JoinRoomR)(nil), "msg.JoinRoomR")
	proto.RegisterType((*LeaveRoom)(nil), "msg.LeaveRoom")
	proto.RegisterType((*LeaveRoomR)(nil), "msg.LeaveRoomR")
	proto.RegisterType((*GrabBanker)(nil), "msg.GrabBanker")
	proto.RegisterType((*Bet)(nil), "msg.Bet")
	proto.RegisterType((*BetR)(nil), "msg.BetR")
	proto.RegisterType((*AutoBet)(nil), "msg.AutoBet")
	proto.RegisterType((*AutoBetR)(nil), "msg.AutoBetR")
	proto.RegisterType((*Error)(nil), "msg.Error")
}

func init() { proto.RegisterFile("bcbm.proto", fileDescriptor_f920c4c0d180b49f) }

var fileDescriptor_f920c4c0d180b49f = []byte{
	// 942 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0x5e, 0xc7, 0xf9, 0x63, 0x9f, 0x26, 0xe9, 0x74, 0x7e, 0xab, 0x95, 0x55, 0xfd, 0x40, 0x59,
	0xaf, 0x80, 0xa8, 0x88, 0x4a, 0x2c, 0x97, 0x5c, 0xc5, 0xe9, 0x6a, 0x5b, 0x54, 0xaf, 0xca, 0x74,
	0x61, 0xaf, 0xdd, 0x64, 0x6a, 0xac, 0x4d, 0x66, 0x56, 0x9e, 0x71, 0xa1, 0x3c, 0x01, 0x97, 0x5c,
	0xf1, 0x08, 0x3c, 0x00, 0x6f, 0xb1, 0x20, 0xf1, 0x08, 0x3c, 0x0b, 0x9a, 0xe3, 0x19, 0xc7, 0x4d,
	0x5a, 0x10, 0x57, 0x9d, 0xef, 0x3b, 0x67, 0x3e, 0x7f, 0xe7, 0xcc, 0x99, 0x49, 0x01, 0xae, 0x16,
	0x57, 0xeb, 0xe3, 0x77, 0xa5, 0xd4, 0x92, 0xfa, 0x6b, 0x95, 0xc7, 0x7d, 0xe8, 0x5e, 0x14, 0xa2,
	0xfe, 0x2b, 0x45, 0x1e, 0xff, 0xea, 0x41, 0xf0, 0x8d, 0xe2, 0xe5, 0x99, 0xb8, 0x96, 0xf4, 0x09,
	0xf4, 0x71, 0x7d, 0x12, 0x79, 0x13, 0x6f, 0x3a, 0x62, 0x16, 0xd1, 0xc7, 0xd0, 0x4b, 0xa5, 0xe0,
	0xb7, 0x51, 0x67, 0xe2, 0x4d, 0x3d, 0x56, 0x03, 0x93, 0x3d, 0xbb, 0xc9, 0x74, 0x56, 0x46, 0xfe,
	0xc4, 0x9b, 0x86, 0xcc, 0x22, 0x7a, 0x08, 0xc1, 0xab, 0x62, 0xf1, 0xf6, 0x55, 0xb6, 0xe6, 0x51,
	0x17, 0x23, 0x0d, 0xa6, 0xff, 0x87, 0x30, 0xe1, 0x7a, 0xb6, 0x96, 0x95, 0xd0, 0x51, 0x0f, 0xd5,
	0x36, 0x84, 0xd9, 0xf9, 0xa6, 0x10, 0x73, 0x0c, 0xf6, 0xd1, 0x41, 0x83, 0xe3, 0xbf, 0x3c, 0x08,
	0x98, 0x94, 0x6b, 0x67, 0x14, 0xd7, 0x8d, 0xd1, 0x1a, 0x19, 0x3e, 0x2d, 0x44, 0xc2, 0x35, 0x3a,
	0x1d, 0x31, 0x8b, 0x90, 0xcf, 0x7e, 0x30, 0xbc, 0x6f, 0x79, 0x44, 0xe6, 0x83, 0x69, 0x21, 0xce,
	0x8b, 0x75, 0xa1, 0xd1, 0xea, 0x88, 0x35, 0xd8, 0xec, 0xb9, 0xd4, 0x99, 0xae, 0x14, 0xfa, 0x1c,
	0x31, 0x8b, 0x68, 0x04, 0x83, 0x17, 0x62, 0xf9, 0xba, 0x58, 0x73, 0xeb, 0xd1, 0x41, 0x13, 0x39,
	0x2d, 0x94, 0x96, 0xe5, 0x6d, 0x34, 0x98, 0xf8, 0x26, 0x62, 0x21, 0x8d, 0x61, 0x78, 0x5a, 0x28,
	0x23, 0x50, 0x28, 0x5d, 0x2c, 0xa2, 0x00, 0xc3, 0x77, 0xb8, 0xf8, 0x67, 0x0f, 0x86, 0xa6, 0x8c,
	0xf9, 0x77, 0x99, 0xc8, 0xf9, 0x69, 0xf2, 0x4f, 0x45, 0x5a, 0x63, 0x9d, 0x87, 0x8c, 0xf9, 0x77,
	0x8d, 0x19, 0x25, 0xae, 0xaa, 0x95, 0x2b, 0xd2, 0x22, 0xfa, 0x21, 0xc0, 0x25, 0x2f, 0x6f, 0x78,
	0x89, 0x9b, 0xea, 0x32, 0x5b, 0x4c, 0xfc, 0x67, 0x07, 0x82, 0x84, 0x6b, 0xd3, 0xf2, 0x84, 0x1e,
	0x01, 0xa9, 0x8f, 0x29, 0xe1, 0xe2, 0xc7, 0x97, 0x72, 0xb5, 0xe4, 0x02, 0x8d, 0x79, 0x6c, 0x87,
	0x37, 0xc2, 0x1b, 0xce, 0x4e, 0x4d, 0x8b, 0xa1, 0x53, 0xd8, 0xb7, 0x28, 0x7d, 0x63, 0xa5, 0x7c,
	0x4c, 0xda, 0xa6, 0xcd, 0xc0, 0x34, 0x14, 0xba, 0xf7, 0xd8, 0x86, 0xd8, 0x78, 0x9a, 0x55, 0xcb,
	0xc2, 0x0a, 0xf5, 0xda, 0x9e, 0x36, 0xfc, 0xc6, 0x93, 0xe1, 0xf0, 0xe8, 0x1a, 0x4f, 0x86, 0xa1,
	0x1f, 0xc3, 0xb8, 0x46, 0xdf, 0x3a, 0x4b, 0x03, 0xcc, 0xd9, 0x62, 0xcd, 0xcc, 0x38, 0x26, 0x0a,
	0x30, 0xa3, 0xc1, 0x5b, 0x0d, 0x0d, 0x77, 0x1a, 0xfa, 0x35, 0x04, 0x49, 0x26, 0xde, 0xf2, 0x52,
	0x25, 0xf4, 0x23, 0xe8, 0x9f, 0xf0, 0x6c, 0xc5, 0xcb, 0xc8, 0x9b, 0xf8, 0xd3, 0xbd, 0xe7, 0xa3,
	0xe3, 0xb5, 0xca, 0x8f, 0xdd, 0x5d, 0x64, 0x36, 0xb8, 0x25, 0xd9, 0xd9, 0x91, 0xbc, 0x84, 0xe0,
	0x62, 0x95, 0xdd, 0xa2, 0xe4, 0x27, 0x30, 0xb0, 0xeb, 0xfb, 0x35, 0x5d, 0xf4, 0x5f, 0x45, 0xbf,
	0x84, 0xde, 0xb9, 0xcc, 0x0b, 0xf1, 0xe0, 0x8b, 0x70, 0x08, 0xc1, 0x45, 0xa6, 0xd4, 0xf7, 0xb2,
	0x5c, 0xe2, 0xf6, 0x90, 0x35, 0x38, 0x7e, 0x06, 0x21, 0x6e, 0x7e, 0xcd, 0x95, 0x7e, 0x48, 0x20,
	0xfe, 0xc9, 0x83, 0x3e, 0x66, 0x31, 0xfa, 0x14, 0xba, 0x86, 0xc4, 0x84, 0x1d, 0xcb, 0x18, 0x6a,
	0x5d, 0x85, 0xce, 0x9d, 0xab, 0xf0, 0x0c, 0x7a, 0x66, 0xa5, 0x22, 0xbf, 0x55, 0xae, 0x7b, 0x25,
	0x58, 0x1d, 0xdb, 0x2a, 0xb6, 0xbb, 0x53, 0x6c, 0x80, 0x4e, 0x64, 0xa5, 0xe3, 0x10, 0x06, 0xf5,
	0x8a, 0xc5, 0x31, 0x04, 0x5f, 0xc9, 0x42, 0x18, 0x85, 0x87, 0x2e, 0x62, 0xfc, 0x9b, 0x07, 0xa1,
	0x4b, 0x62, 0xf4, 0x33, 0x80, 0x79, 0x55, 0xd6, 0xa7, 0xa6, 0xee, 0x2f, 0xa6, 0x95, 0x60, 0xd3,
	0xed, 0xed, 0xc2, 0xb2, 0x5c, 0xba, 0xbb, 0x71, 0xac, 0x95, 0xd0, 0x3e, 0x5a, 0xff, 0x3f, 0x1c,
	0xed, 0x6e, 0xb5, 0x7b, 0x10, 0x9e, 0xf3, 0xec, 0x86, 0x1b, 0xd3, 0xf1, 0x10, 0xa0, 0x01, 0xcc,
	0xa0, 0x97, 0x65, 0x76, 0x55, 0x4f, 0x68, 0xfc, 0x39, 0xf8, 0xe6, 0x89, 0xa4, 0xd0, 0x9d, 0x95,
	0x3c, 0xb3, 0xa5, 0xe3, 0x1a, 0x5f, 0xfe, 0xfa, 0x09, 0xaf, 0xaf, 0xb6, 0x45, 0xe6, 0x47, 0x25,
	0xe1, 0x9a, 0x99, 0x3e, 0xce, 0x2a, 0x2d, 0x13, 0xae, 0x63, 0x80, 0xc0, 0x2e, 0x59, 0xfc, 0x29,
	0xf4, 0x5e, 0x94, 0xa5, 0x2c, 0x69, 0x0c, 0xdd, 0xb9, 0x5c, 0x72, 0xd4, 0x1c, 0x3f, 0x1f, 0x63,
	0x25, 0x18, 0x31, 0x2c, 0xc3, 0xd8, 0xd1, 0xfb, 0x0e, 0x84, 0x29, 0x57, 0x2a, 0xcb, 0xf9, 0xd9,
	0x09, 0x1d, 0x42, 0x90, 0xaa, 0x1c, 0x73, 0xc8, 0x23, 0xba, 0x07, 0x83, 0x54, 0xe5, 0xe6, 0x77,
	0x8c, 0x78, 0x0e, 0x48, 0x91, 0x93, 0x0e, 0x25, 0x30, 0x4c, 0x55, 0xde, 0x8c, 0x1f, 0xf1, 0xed,
	0x4e, 0x64, 0x48, 0x97, 0x8e, 0x20, 0x74, 0x88, 0x91, 0xde, 0x06, 0xca, 0x4a, 0x93, 0x3e, 0x1d,
	0x03, 0x34, 0x90, 0x91, 0x01, 0xdd, 0x87, 0xbd, 0x54, 0xe5, 0xee, 0x88, 0x49, 0x60, 0xe5, 0x9b,
	0x33, 0x27, 0xa1, 0xfb, 0xa0, 0x6b, 0x22, 0x01, 0x7a, 0x00, 0xa3, 0x36, 0xc3, 0xc8, 0x9e, 0xa5,
	0x36, 0xbd, 0x25, 0x43, 0xfb, 0x29, 0xdb, 0x1a, 0x32, 0xb2, 0x9f, 0x72, 0xad, 0x22, 0x63, 0x0a,
	0xd0, 0x4f, 0x55, 0x6e, 0x82, 0xfb, 0xb6, 0x44, 0x0c, 0x10, 0x9b, 0xe9, 0x86, 0x84, 0x1c, 0x38,
	0xc2, 0xbe, 0x2b, 0x84, 0x5a, 0xc2, 0xbd, 0x0a, 0xe4, 0x7f, 0x47, 0xbf, 0x78, 0x10, 0x36, 0xfd,
	0x35, 0x6a, 0x97, 0xd5, 0x62, 0xc1, 0x95, 0x22, 0x8f, 0xe8, 0x53, 0xf8, 0xe0, 0x4c, 0xa8, 0xea,
	0xfa, 0xba, 0x58, 0x14, 0x5c, 0xe8, 0x24, 0x5b, 0x65, 0x62, 0xc1, 0x8d, 0xd5, 0x7a, 0x50, 0x09,
	0xa7, 0x87, 0xf0, 0xe4, 0x9e, 0x14, 0xe3, 0xec, 0x9a, 0x1e, 0xc0, 0xb0, 0x9e, 0xad, 0xf9, 0x4a,
	0x2a, 0xbe, 0x24, 0xef, 0x3d, 0xfa, 0x18, 0xf6, 0xcd, 0x54, 0x32, 0xfe, 0x8e, 0x67, 0xba, 0xee,
	0xfb, 0xef, 0x2d, 0x76, 0x2d, 0x35, 0xaf, 0xd9, 0x3f, 0xbc, 0xab, 0x3e, 0xfe, 0x67, 0xf2, 0xc5,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xdd, 0x14, 0x04, 0xa7, 0x08, 0x00, 0x00,
}
